# base image
## pass this via docker build --build-arg node_version=22
ARG node_version=22
FROM node:${node_version}-bookworm-slim

# basic tools + google chrome + git
RUN apt-get update \
    && apt-get install -yq --no-install-recommends \
    libgconf-2-4 gnupg2 wget ca-certificates lsb-release \
    software-properties-common vim procps git \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && wget -O- https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor > /etc/apt/trusted.gpg.d/google.gpg \
    && apt-get update \
    && apt-get install -y --no-install-recommends google-chrome-stable \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

# copy sample app to /app
COPY ./examples/ui5-js-app/webapp webapp
COPY ./examples/ui5-js-app/scripts scripts
COPY ./examples/ui5-js-app/ui5.yaml ui5.yaml
COPY ./examples/reusable-test-scripts/dist/esm/ui5-local-apps webapp/test/e2e
COPY ./docker/package-standalone.json package.json
# this is the standard file and allows for a simple call like "wdio"
COPY ./docker/e2e-test-config e2e-test-config
RUN mkdir -p report/screenshots

# install basic setup:
# - local minimal WebdriverIO environment
#   and setup, incl standard reporter + Chrome
# - wdi5
RUN npm install

# run wdio + wdi5
CMD ["npm", "run", "start:test"]
